//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ASP_RoundTrip_OOP_OnlineShopping.Models.DomainModels.DTO.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnlineShoppingEntities : DbContext
    {
        public OnlineShoppingEntities()
            : base("name=OnlineShoppingEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Product> Product { get; set; }
    
        public virtual int USP_Category_CreateTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Category_CreateTable");
        }
    
        public virtual int USP_Category_Delete(ObjectParameter outputResult)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Category_Delete", outputResult);
        }
    
        public virtual int USP_Category_Edit(ObjectParameter outputResult)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Category_Edit", outputResult);
        }
    
        public virtual int USP_Category_Insert(ObjectParameter outputResult)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Category_Insert", outputResult);
        }
    
        public virtual ObjectResult<USP_Category_List_Result> USP_Category_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Category_List_Result>("USP_Category_List");
        }
    
        public virtual int USP_Category_Select(ObjectParameter outputResult)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Category_Select", outputResult);
        }
    
        public virtual int USP_Product_CreateTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Product_CreateTable");
        }
    
        public virtual int USP_Product_Delete()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Product_Delete");
        }
    
        public virtual int USP_Product_Edit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Product_Edit");
        }
    
        public virtual int USP_Product_Insert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Product_Insert");
        }
    
        public virtual ObjectResult<USP_Product_List_Result> USP_Product_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Product_List_Result>("USP_Product_List");
        }
    
        public virtual int USP_Product_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Product_Select");
        }
    }
}
