//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ASP_RoundTrip_OOP_OnlineShopping.Models.DomainModels.DTO.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string NationalCode { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string ContactEmail { get; set; }
        public string MobileNumber { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
    }
}
